// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfxlzjhvrnyjylyuimis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeGx6amh2cm55anlseXVpbWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NDE3OTksImV4cCI6MjA1MjAxNzc5OX0.SkTErHtqNTZAeJa-IurGlfZvgdOuHHW0DYjiB3ndaRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);